export const products = [
  {
    slug: "classic-choco-chip-cookie",
    nameEn: "COOKIELICIOUS Classic Choco Chip Cookie",
    shortNameEn: "Classic Choco Chip Cookie",
    nameAr: "كوكيز شوكو تشيب كلاسيك",
    shortNameAr: "كوكيز شوكو تشيب كلاسيك",
    price: "IQD 3,000",
    numericPrice: 3000,
    oldPrice: "IQD 3,000",
    badgeAEn: "New",
    badgeAAr: "جديد",
    badgeBEn: "Deal",
    badgeBAr: "عرض",
    categoryEn: "Cookies",
    categoryAr: "كوكيز",
    descriptionEn: "Premium cookie with a rich buttery dough and loaded chocolate chips.",
    descriptionAr: "كوكيز فاخر بعجينة غنية بالزبدة ومليء بقطع الشوكولاتة.",
    optionKeys: ["single", "box4", "box6", "box12"],
    optionsEn: ["Single", "Box of 4", "Box of 6", "Box of 12"],
    optionsAr: ["حبة واحدة", "علبة 4", "علبة 6", "علبة 12"]
  },
  {
    slug: "lotus-biscoff-cookie",
    nameEn: "COOKIELICIOUS Lotus Biscoff Cookie",
    shortNameEn: "Lotus Biscoff Cookie",
    nameAr: "كوكيز لوتس بيسكوف",
    shortNameAr: "كوكيز لوتس بيسكوف",
    price: "IQD 3,500",
    numericPrice: 3500,
    oldPrice: "IQD 3,500",
    badgeAEn: "New",
    badgeAAr: "جديد",
    badgeBEn: "Deal",
    badgeBAr: "عرض",
    categoryEn: "Cookies",
    categoryAr: "كوكيز",
    descriptionEn: "Premium cookie with lotus flavor and a soft center.",
    descriptionAr: "كوكيز فاخر بنكهة اللوتس وقلب طري.",
    optionKeys: ["single", "box4", "box6", "box12"],
    optionsEn: ["Single", "Box of 4", "Box of 6", "Box of 12"],
    optionsAr: ["حبة واحدة", "علبة 4", "علبة 6", "علبة 12"]
  },
  {
    slug: "double-chocolate-cookie",
    nameEn: "COOKIELICIOUS Double Chocolate Cookie",
    shortNameEn: "Double Chocolate Cookie",
    nameAr: "كوكيز دبل شوكليت",
    shortNameAr: "كوكيز دبل شوكليت",
    price: "IQD 3,500",
    numericPrice: 3500,
    oldPrice: "IQD 3,500",
    badgeAEn: "New",
    badgeAAr: "جديد",
    badgeBEn: "Deal",
    badgeBAr: "عرض",
    categoryEn: "Cookies",
    categoryAr: "كوكيز",
    descriptionEn: "Premium cookie for chocolate lovers with a rich cocoa flavor.",
    descriptionAr: "كوكيز فاخر لعشاق الشوكولاتة بنكهة كاكاو غنية.",
    optionKeys: ["single", "box4", "box6", "box12"],
    optionsEn: ["Single", "Box of 4", "Box of 6", "Box of 12"],
    optionsAr: ["حبة واحدة", "علبة 4", "علبة 6", "علبة 12"]
  },
  {
    slug: "red-velvet-cookie",
    nameEn: "COOKIELICIOUS Red Velvet Cookie",
    shortNameEn: "Red Velvet Cookie",
    nameAr: "كوكيز ريد فيلفت",
    shortNameAr: "كوكيز ريد فيلفت",
    price: "IQD 3,500",
    numericPrice: 3500,
    oldPrice: "IQD 3,500",
    badgeAEn: "New",
    badgeAAr: "جديد",
    badgeBEn: "Deal",
    badgeBAr: "عرض",
    categoryEn: "Cookies",
    categoryAr: "كوكيز",
    descriptionEn: "Premium red velvet cookie with a soft texture and dessert-shop finish.",
    descriptionAr: "كوكيز ريد فيلفت فاخر بقوام طري ولمسة حلويات مميزة.",
    optionKeys: ["single", "box4", "box6", "box12"],
    optionsEn: ["Single", "Box of 4", "Box of 6", "Box of 12"],
    optionsAr: ["حبة واحدة", "علبة 4", "علبة 6", "علبة 12"]
  },
  {
    slug: "oreo-cream-cookie",
    nameEn: "COOKIELICIOUS Oreo Cream Cookie",
    shortNameEn: "Oreo Cream Cookie",
    nameAr: "كوكيز أوريو كريم",
    shortNameAr: "كوكيز أوريو كريم",
    price: "IQD 3,500",
    numericPrice: 3500,
    oldPrice: "IQD 3,500",
    badgeAEn: "New",
    badgeAAr: "جديد",
    badgeBEn: "Deal",
    badgeBAr: "عرض",
    categoryEn: "Cookies",
    categoryAr: "كوكيز",
    descriptionEn: "Premium oreo cookie with a creamy filling-inspired taste.",
    descriptionAr: "كوكيز أوريو فاخر بطعم كريمي مستوحى من الحشوة.",
    optionKeys: ["single", "box4", "box6", "box12"],
    optionsEn: ["Single", "Box of 4", "Box of 6", "Box of 12"],
    optionsAr: ["حبة واحدة", "علبة 4", "علبة 6", "علبة 12"]
  },
  {
    slug: "pistachio-cookie",
    nameEn: "COOKIELICIOUS Pistachio Cookie",
    shortNameEn: "Pistachio Cookie",
    nameAr: "كوكيز فستق",
    shortNameAr: "كوكيز فستق",
    price: "IQD 4,000",
    numericPrice: 4000,
    oldPrice: "IQD 4,000",
    badgeAEn: "New",
    badgeAAr: "جديد",
    badgeBEn: "Limited",
    badgeBAr: "محدود",
    categoryEn: "Cookies",
    categoryAr: "كوكيز",
    descriptionEn: "Premium pistachio cookie with a smooth nutty finish.",
    descriptionAr: "كوكيز فستق فاخر بنكهة ناعمة ولمسة مكسرات غنية.",
    optionKeys: ["single", "box4", "box6", "box12"],
    optionsEn: ["Single", "Box of 4", "Box of 6", "Box of 12"],
    optionsAr: ["حبة واحدة", "علبة 4", "علبة 6", "علبة 12"]
  },
  {
    slug: "smores-cookie",
    nameEn: "COOKIELICIOUS S’mores Cookie",
    shortNameEn: "S’mores Cookie",
    nameAr: "كوكيز سمورز",
    shortNameAr: "كوكيز سمورز",
    price: "IQD 4,000",
    numericPrice: 4000,
    oldPrice: "IQD 4,000",
    badgeAEn: "New",
    badgeAAr: "جديد",
    badgeBEn: "Deal",
    badgeBAr: "عرض",
    categoryEn: "Cookies",
    categoryAr: "كوكيز",
    descriptionEn: "Premium s’mores cookie with toasted sweetness and rich chocolate flavor.",
    descriptionAr: "كوكيز سمورز فاخر بحلاوة محمصة ونكهة شوكولاتة غنية.",
    optionKeys: ["single", "box4", "box6", "box12"],
    optionsEn: ["Single", "Box of 4", "Box of 6", "Box of 12"],
    optionsAr: ["حبة واحدة", "علبة 4", "علبة 6", "علبة 12"]
  },
  {
    slug: "nutella-cookie",
    nameEn: "COOKIELICIOUS Nutella Cookie",
    shortNameEn: "Nutella Cookie",
    nameAr: "كوكيز نوتيلا",
    shortNameAr: "كوكيز نوتيلا",
    price: "IQD 4,000",
    numericPrice: 4000,
    oldPrice: "IQD 4,000",
    badgeAEn: "New",
    badgeAAr: "جديد",
    badgeBEn: "Limited",
    badgeBAr: "محدود",
    categoryEn: "Cookies",
    categoryAr: "كوكيز",
    descriptionEn: "Premium nutella cookie with a rich hazelnut chocolate taste.",
    descriptionAr: "كوكيز نوتيلا فاخر بطعم شوكولاتة وبندق غني.",
    optionKeys: ["single", "box4", "box6", "box12"],
    optionsEn: ["Single", "Box of 4", "Box of 6", "Box of 12"],
    optionsAr: ["حبة واحدة", "علبة 4", "علبة 6", "علبة 12"]
  }
];

export function getProductBySlug(slug) {
  return products.find((product) => product.slug === slug);
}
